-- MySQL Script generated by MySQL Workbench
-- Fri Dec  6 18:39:23 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdgastos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdgastos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdgastos` DEFAULT CHARACTER SET utf8 ;
USE `bdgastos` ;

-- -----------------------------------------------------
-- Table `bdgastos`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgastos`.`usuarios` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`, `email`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdgastos`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgastos`.`categorias` (
  `idcategorias` INT NOT NULL AUTO_INCREMENT,
  `nombreCategoria` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdgastos`.`gastos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgastos`.`gastos` (
  `idgastos` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `anho` INT NOT NULL,
  `mes` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL,
  `categorias_idcategorias` INT NOT NULL,
  `usuarios_idusuario` INT NOT NULL,
  PRIMARY KEY (`idgastos`, `categorias_idcategorias`, `usuarios_idusuario`),
  INDEX `fk_gastos_categorias1_idx` (`categorias_idcategorias` ASC) VISIBLE,
  INDEX `fk_gastos_usuarios1_idx` (`usuarios_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_gastos_categorias1`
    FOREIGN KEY (`categorias_idcategorias`)
    REFERENCES `bdgastos`.`categorias` (`idcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gastos_usuarios1`
    FOREIGN KEY (`usuarios_idusuario`)
    REFERENCES `bdgastos`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdgastos`.`objetivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgastos`.`objetivos` (
  `idobjetivos` INT NOT NULL AUTO_INCREMENT,
  `objetivo` VARCHAR(45) NOT NULL,
  `porcentaje` INT NOT NULL,
  `cantidad` DECIMAL(7,2) NOT NULL,
  `ahorrado` DECIMAL(7,2) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `mes` VARCHAR(45) NOT NULL,
  `anho` INT NOT NULL,
  `usuarios_idusuario` INT NOT NULL,
  PRIMARY KEY (`idobjetivos`, `usuarios_idusuario`),
  INDEX `fk_objetivos_usuarios1_idx` (`usuarios_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_objetivos_usuarios1`
    FOREIGN KEY (`usuarios_idusuario`)
    REFERENCES `bdgastos`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdgastos`.`ingresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdgastos`.`ingresos` (
  `idingresos` INT NOT NULL AUTO_INCREMENT,
  `anho` INT NOT NULL,
  `mes` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL,
  `usuarios_idusuario` INT NOT NULL,
  `categorias_idcategorias` INT NOT NULL,
  PRIMARY KEY (`idingresos`, `usuarios_idusuario`, `categorias_idcategorias`),
  UNIQUE INDEX `idingresos_UNIQUE` (`idingresos` ASC) VISIBLE,
  INDEX `fk_ingresos_usuarios1_idx` (`usuarios_idusuario` ASC) VISIBLE,
  INDEX `fk_ingresos_categorias1_idx` (`categorias_idcategorias` ASC) VISIBLE,
  CONSTRAINT `fk_ingresos_usuarios1`
    FOREIGN KEY (`usuarios_idusuario`)
    REFERENCES `bdgastos`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingresos_categorias1`
    FOREIGN KEY (`categorias_idcategorias`)
    REFERENCES `bdgastos`.`categorias` (`idcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
